/* eslint-disable no-shadow */
export enum ParameterSelectionStoreActions {
  SET_SCENARIO_DEFINITION = 'SET_SCENARIO_DEFINITION',
  SET_SCENARIO_PARAMETERS = 'SET_SCENARIO_PARAMETERS',
  SET_SCENARIO_DEFINITION_MODE = 'SET_SCENARIO_DEFINITION_MODE',
  RESET_CURRENT_SELECTED_PARAMETER = 'RESET_CURRENT_SELECTED_PARAMETER',
}
export enum ParameterSelectionStoreGetters {
  PARAMETERS_HAVE_CHANGED = 'PARAMETERS_HAVE_CHANGED',
  CAN_RUN = 'CAN_RUN',
}
export enum ParameterSelectionStoreMutations {
  CHANGE_CURRENT_SELECTED_PARAMETER = 'CHANGE_CURRENT_SELECTED_PARAMETER',
  RESET_CURRENT_SELECTED_PARAMETER = 'RESET_CURRENT_SELECTED_PARAMETER',
  CHANGE_CURRENT_PARAMETER_TYPE = 'CHANGE_CURRENT_PARAMETER_TYPE',
  SET_SCENARIO_DEFINITION = 'SET_SCENARIO_DEFINITION',
  SET_SCENARIO_PARAMETERS = 'SET_SCENARIO_PARAMETERS',
  SET_SCENARIO_DEFINITION_MODE = 'SET_SCENARIO_DEFINITION_MODE',
}
