name: Publish ASP.NET Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: dotnet build Battelle.EPA.WideAreaDecon.API/Battelle.EPA.WideAreaDecon.API.csproj -c Release

    - name: Test .NET
      run: dotnet test Battelle.EPA.WideAreaDecon.API.Tests/Battelle.EPA.WideAreaDecon.API.Tests.csproj --no-build -c Release --verbosity normal
    
    - name: Publish
      run: dotnet publish Battelle.EPA.WideAreaDecon.API/Battelle.EPA.WideAreaDecon.API.csproj --no-build -c Release -o ./publish

    - name: Copy Build Files
      run: cp -R ./Battelle.EPA.WideAreaDecon.API/bin/Release/net6.0/gdal, ./Battelle.EPA.WideAreaDecon.API/bin/Release/net6.0/Battelle.RiskAssessment.Common.Statistics.Native.*  ./publish

    - name: Test Typescript
      working-directory: Battelle.EPA.WideAreaDecon.Client
      run: npm run test

    - name: Create Archive
      run: Compress-Archive -Path ./publish/* -DestinationPath ./Battelle.EPA.WideAreaDecon.zip

    - name: Create Installer
      run: ./InstallerFiles/Battelle.Common.Utilities.ElectronAppInstallerCreator.exe ./InstallerFiles/CreateInstallerDeconTool.json
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: ./Installer
